routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'Auth\LoginController@showLoginForm')->middleware('guest');
//name=formulario
Auth::routes();

//ruta para login name="nombre de la rura"
Route::post('login','Auth\LoginController@login')->name('login');

Route::get('logout', function(){

    return back();

});

//Route::post('logout','Auth\LoginController@logout')->name('logout');

Route::group(['middleware'=>'auth'],function(){
    Route::get('/home', 'HomeController@index')->name('home');
});

Route::group(['middleware'=>'auth'],function(){
    Route::resource('direcciones','direccionController');
});

Route::group(['middleware'=>'auth'],function(){
    Route::resource('unidades_medida','unidadMedidaController');
});

Route::group(['middleware'=>'auth'],function(){
    Route::resource('programas','programaController');
});

Route::group(['middleware'=>'auth'],function(){
    Route::resource('proyectos','proyectoController');
});

Route::group(['middleware'=>'auth'],function(){
    Route::resource('metas','metaController');
});

Route::group(['middleware'=>'auth'],function(){
    Route::resource('trimestres','trimestreController');
});

Route::group(['middleware'=>'auth'],function(){
    Route::post('trimestres','trimestreController@uploadFile')->name('uploadFile');
});

Route::group(['middleware'=>'auth'],function(){
    Route::delete('trimestres{id}','trimestreController@deleteFileTirmeste')->name('deleteFile');
});

Route::group(['middleware'=>'auth'],function(){
    Route::get('trimestres{id}','trimestreController@edit');
});

Route::group(['middleware'=>'auth'],function(){
    Route::resource('programado','trimestreArchivoController');
});

Route::group(['middleware'=>'auth'],function(){
    Route::resource('usuarios','usuarioController');
});

resources/views/unidades/create.blade.php
@extends('layouts.app')

@section('title','Crear Unidad de Medida')
@section('content')
<div class="content-page">
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="btn-group pull-right">
                            <ol class="breadcrumb hide-phone p-0 m-0"></ol>
                        </div>
                        <h4 class="page-title">Registrar Unidad de Medida</h4>
                        <div class="clearfix"></div>
                        <a href="{{ route('unidades_medida.index') }}"><i class="mdi mdi-keyboard-return"></i> Regresar</a>
                    </div>
                </div>
            </div>
            @include('common.errors')
            <div class="row">
                <div class="col-md-6 offset-md-3 m-t-20">
                    <div class="card-box">
                    {!! Form::open(['route' => 'unidades_medida.store', 'method' => 'POST','class' => 'form-group']) !!}
                    @include('unidades.form')
                    {!! Form::submit('Guardar',['class' => 'btn btn-primary']) !!}
                    {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/unidades/edit.blade.php
@extends('layouts.app')

@section('title','Editar Unidad de Medida')
@section('content')
<div class="content-page">
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="btn-group pull-right">
                            <ol class="breadcrumb hide-phone p-0 m-0"></ol>
                        </div>
                        <h4 class="page-title">Editar Unidad de Medida</h4>
                        <div class="clearfix"></div>
                        <a href="{{ route('unidades_medida.index') }}"><i class="mdi mdi-keyboard-return"></i> Regresar</a>
                    </div>
                </div>
            </div>
            @include('common.errors')
            <div class="row">
                <div class="col-md-6 offset-md-3 m-t-20">
                    <div class="card-box">
                    {!! Form::model($unidad, ['route' => ['unidades_medida.update', $unidad->id], 'method' => 'PUT']) !!}
                    @include('unidades.form')
                    {!! Form::submit('Guardar',['class' => 'btn btn-primary']) !!}
                    {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/unidades/form.blade.php
<div class="form-group">
    {!! Form::label('udnombre', 'Unidad de Medida') !!}
    {!! Form::text('udnombre',null,['class' => 'form-control']) !!}
</div>

resources/views/unidades/index.blade.php
@extends('layouts.app')

@section('title','Unidades de Medida')

@section('content')
<div class="content-page">
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="btn-group pull-right">
                            <ol class="breadcrumb hide-phone p-0 m-0"></ol>
                        </div>
                        <h4 class="page-title">Unidades de Medida</h4>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <a href="{{ route('unidades_medida.create') }}" class="btn btn-success btn-custom waves-effect w-md waves-light m-b-5">Nueva Unidad de Medida</a>
            @include('common.success')
            <div class="row m-t-15">
                @foreach ($unidades as $unidad)
                <div class="col-md-4">
                    <div class="widget-simple-chart text-right card-box text-center">
                        <i class="ti-list-ol"></i>
                        <p class="text-muted text-nowrap m-b-10">{{ $unidad->udnombre }}</p>
                        <hr>
                        <a href="{{url('/unidades_medida/'.$unidad->id.'/edit')}}" class="btn btn-primary btn-sm btn-custom waves-effect w-md waves-light m-b-5">Editar</a>
                    </div>
                </div>
                @endforeach
            </div>
        </div>
    </div>
</div>
@endsection