routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'Auth\LoginController@showLoginForm')->middleware('guest');
//name=formulario
Auth::routes();

//ruta para login name="nombre de la rura"
Route::post('login','Auth\LoginController@login')->name('login');

Route::get('logout', function(){

    return back();

});

//Route::post('logout','Auth\LoginController@logout')->name('logout');

Route::group(['middleware'=>'auth'],function(){
    Route::get('/home', 'HomeController@index')->name('home');
});

Route::group(['middleware'=>'auth'],function(){
    Route::resource('direcciones','direccionController');
});

Route::group(['middleware'=>'auth'],function(){
    Route::resource('unidades_medida','unidadMedidaController');
});

Route::group(['middleware'=>'auth'],function(){
    Route::resource('programas','programaController');
});

Route::group(['middleware'=>'auth'],function(){
    Route::resource('proyectos','proyectoController');
});

Route::group(['middleware'=>'auth'],function(){
    Route::resource('metas','metaController');
});

Route::group(['middleware'=>'auth'],function(){
    Route::resource('trimestres','trimestreController');
});

Route::group(['middleware'=>'auth'],function(){
    Route::post('trimestres','trimestreController@uploadFile')->name('uploadFile');
});

Route::group(['middleware'=>'auth'],function(){
    Route::delete('trimestres{id}','trimestreController@deleteFileTirmeste')->name('deleteFile');
});

Route::group(['middleware'=>'auth'],function(){
    Route::get('trimestres{id}','trimestreController@edit');
});

Route::group(['middleware'=>'auth'],function(){
    Route::resource('programado','trimestreArchivoController');
});

Route::group(['middleware'=>'auth'],function(){
    Route::resource('usuarios','usuarioController');
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Reporte de Metas - @yield('title')</title>
    <!-- MintonCSS -->
    <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('css/icons.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet" type="text/css">
    <style>
    /*PARAMETROS DE ASIGNACIÖN*/
    .rojo{
        background-color: red;
        color:white;
    }
    .naranja{
        background-color:orange;
        color:white;
    }
    .amarilla{
        background-color:yellow;
        color:black;
    }
    .verde{
        background-color: green;
        color:white;
    }
    .morada{
        background-color: blueviolet;
        color:white;
    }
    .ocultar{
        display:none;
    }
    </style>
    <!-- end MintonCSS -->
</head>
<body class="widescreen fixed-left-void">
    <div id="wrapper" class="forced enlarged">
        <!-- incluir menu -->
        @include('layouts.menu')
        <!-- fin de menu -->
        @yield('content')
    </div>
    <!-- MintonJS -->
    <!-- Plugins  -->
    <script src="{{ asset('js/jquery.min.js') }}"></script>
    <script src="{{ asset('js/popper.min.js') }}"></script><!-- Popper for Bootstrap -->
    <script src="{{ asset('js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('js/detect.js') }}"></script>
    <script src="{{ asset('js/fastclick.js') }}"></script>
    <script src="{{ asset('js/jquery.slimscroll.js') }}"></script>
    <script src="{{ asset('js/jquery.blockUI.js') }}"></script>
    <script src="{{ asset('js/waves.js') }}"></script>
    <script src="{{ asset('js/wow.min.js') }}"></script>
    <script src="{{ asset('js/jquery.nicescroll.js') }}"></script>
    <script src="{{ asset('js/jquery.slimscroll.js') }}"></script>
    <script src="{{ asset('js/jquery.scrollTo.min.js') }}"></script>
    <!-- Custom main Js -->
    <script src="{{ asset('js/jquery.core.js') }}"></script>
    <script src="{{ asset('js/jquery.app.js') }}"></script>
    <!-- end MintonJS -->
</body>
</html>

resources/views/layouts/menu.blade.php
<!-- Top Bar Start -->
<div class="topbar">

    <!-- LOGO -->
    <div class="topbar-left">
        <div class="text-center">
            <a href="#" class="logo"><i class="ti"></i> <span>Reporte de Metas</span></a>
        </div>
    </div>

    <!-- Button mobile view to collapse sidebar menu -->
    <nav class="navbar-custom">

        <ul class="list-inline float-right mb-0">
                <img src="{{ asset('/images/logo_login.png') }}" alt="" width="320px">
            <!--<li class="list-inline-item dropdown notification-list">
                <a class="nav-link dropdown-toggle arrow-none waves-light waves-effect" data-toggle="dropdown" href="#" role="button"
                    aria-haspopup="false" aria-expanded="false">
                    <i class="mdi mdi-bell noti-icon"></i>
                    <span class="badge badge-pink noti-icon-badge">0</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-arrow dropdown-menu-lg" aria-labelledby="Preview">
                    
                    <div class="dropdown-item noti-title">
                        <h5 class="font-16"><span class="badge badge-danger float-right">5</span>Notificaciones</h5>
                    </div>

                    
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <div class="notify-icon bg-success"><i class="mdi mdi-comment-account"></i></div>
                        <p class="notify-details">Robert S. Taylor commented on Admin<small class="text-muted">1 min ago</small></p>
                    </a>

                    
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <div class="notify-icon bg-info"><i class="mdi mdi-account"></i></div>
                        <p class="notify-details">New user registered.<small class="text-muted">1 min ago</small></p>
                    </a>

                    
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <div class="notify-icon bg-danger"><i class="mdi mdi-airplane"></i></div>
                        <p class="notify-details">Carlos Crouch liked <b>Admin</b><small class="text-muted">1 min ago</small></p>
                    </a>

                    
                    <a href="javascript:void(0);" class="dropdown-item notify-item notify-all">
                        View All
                    </a>

                </div>
            </li>-->

            <li class="list-inline-item dropdown notification-list">
                <a class="nav-link dropdown-toggle waves-effect waves-light nav-user" data-toggle="dropdown" href="#" role="button"
                    aria-haspopup="false" aria-expanded="false">
                    <i class="mdi mdi-account-circle"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right profile-dropdown " aria-labelledby="Preview">
                    <!-- item-->
                    <a class="dropdown-item notify-item" href="{{ route('logout') }}"
                        onclick="event.preventDefault();
                                        document.getElementById('logout-form').submit();">
                        <i class="mdi mdi-logout"></i>
                        {{ __('Salir') }}
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </div>
            </li>

        </ul>

        <ul class="list-inline menu-left mb-0">
            <li class="float-left">
                <button class="button-menu-mobile open-left waves-light waves-effect">
                    <i class="mdi mdi-menu"></i>
                </button>
            </li>
        </ul>

    </nav>

</div>
<!-- Top Bar End -->

<!-- ========== Left Sidebar Start ========== -->

<div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">
        <!--- Divider -->
        <div id="sidebar-menu">
            <ul>
                <li class="menu-title">Main</li>

                <li>
                    <a href="{{ route('home') }}" class="waves-effect waves-primary"><i class="ti-home"></i><span> Inicio </span></a>
                </li>
                @if(Auth::user()->rol == 'Administrador')
                    <li class="has_sub">
                        <a href="{{ route('direcciones.index')}}" class="waves-effect"><i class="ti-agenda"></i><span>Direcciones</span> <span class="menu-arrow"></span></a>
                    </li>
                @endif
                @if(Auth::user()->rol == 'Administrador')
                <li class="has_sub">
                    <a href="{{ route('unidades_medida.index') }}" class="waves-effect"><i class="ti-list-ol"></i><span>Unidad de medida</span> <span class="menu-arrow"></span></a>
                </li>
                @endif
                @if(Auth::user()->rol == 'Administrador')
                <li class="has_sub">
                    <a href="{{ route('programas.index') }}" class="waves-effect"><i class="ti-folder"></i><span>Programas</span> <span class="menu-arrow"></span></a>
                </li>
                @endif
                @if(Auth::user()->rol == 'Administrador')
                <li class="has_sub">
                    <a href="{{ route('proyectos.index') }}" class="waves-effect"><i class="ti-agenda"></i><span>Proyectos</span> <span class="menu-arrow"></span></a>
                </li>
                @endif
                <li class="has_sub">
                    <a href="{{ route('metas.index') }}" class="waves-effect"><i class="ti-bar-chart"></i><span>Metas</span> <span class="menu-arrow"></span></a>
                </li>
                @if(Auth::user()->rol == 'Administrador')
                <li class="has_sub">
                    <a href="{{ route('usuarios.index') }}" class="waves-effect"><i class="ti-user"></i><span>Usuarios</span></a>
                </li>
                @endif
            </ul>

            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<!-- Left Sidebar End -->

resources/views/layouts/start.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Reporte de Metas - @yield('title')</title>
    <!-- MintonCSS -->
    <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('css/icons.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet" type="text/css">
    <!-- end MintonCSS -->
</head>
<body>
    <div class="wrapper-page">
        @yield('content')
    </div>
    <!-- MintonJS -->
    <!-- Plugins  -->
    <script src="{{ asset('js/jquery.min.js') }}"></script>
    <script src="{{ asset('js/bootstrap.min.js') }}"></script>
    <!-- Custom main Js -->
    <script src="assets/js/jquery.core.js"></script>
    <script src="assets/js/jquery.app.js"></script>
    <!-- end MintonJS -->
</body>
</html>